DEMO {
    main
    blinkRed
    blinkGreen
}

IRQ {
    SWI -> _.PORT.vPortYieldProcessor
    TMR -> _.PORT.vTickISR
}

FREERTOS {
    vTaskStartScheduler
    vTaskSwitchContext
    xTaskIncrementTick
    vTaskDelay
}

PORT {
    xPortStartScheduler
    prvSetupTimerInterrupt
    vPortISRStartFirstTask
    portSAVE_CONTEXT
    portRESTORE_CONTEXT
    vTickISR
    vPortYieldProcessor

    vPortYieldProcessor -> portSAVE_CONTEXT
    vPortYieldProcessor -> _.FREERTOS.vTaskSwitchContext
    vPortYieldProcessor -> portRESTORE_CONTEXT
}


DEMO.main -> FREERTOS.vTaskStartScheduler
FREERTOS.vTaskStartScheduler -> PORT.xPortStartScheduler
PORT.xPortStartScheduler -> PORT.prvSetupTimerInterrupt
PORT.xPortStartScheduler -> PORT.vPortISRStartFirstTask
PORT.vPortISRStartFirstTask -> PORT.portRESTORE_CONTEXT

PORT.vTickISR -> PORT.portSAVE_CONTEXT
PORT.vTickISR -> PORT.portRESTORE_CONTEXT
PORT.vTickISR -> FREERTOS.xTaskIncrementTick
PORT.vTickISR -> FREERTOS.vTaskSwitchContext

DEMO.blinkRed -> FREERTOS.vTaskDelay
DEMO.blinkGreen -> FREERTOS.vTaskDelay
FREERTOS.vTaskDelay -> IRQ.SWI

