DEMO.main -> FREERTOS.vTaskStartScheduler
FREERTOS.vTaskStartScheduler -> PORT.xPortStartScheduler
PORT.xPortStartScheduler -> PORT.prvSetupTimerInterrupt
PORT.xPortStartScheduler -> PORT.vPortISRStartFirstTask
PORT.vPortISRStartFirstTask -> PORT.portRESTORE_CONTEXT
